// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz09Fh9bwTepccfQUuwPKsguYnCh8ZMxI',
    appId: '1:755189938867:web:9e4f71f7dd75ca0c5d8ec6',
    messagingSenderId: '755189938867',
    projectId: 'let-schat-99db5',
    authDomain: 'let-schat-99db5.firebaseapp.com',
    storageBucket: 'let-schat-99db5.appspot.com',
    measurementId: 'G-792JJKVE8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UHSPxJNXI4Khx7DHEAir2hBw-a0DbLY',
    appId: '1:755189938867:android:4a33ea53568475905d8ec6',
    messagingSenderId: '755189938867',
    projectId: 'let-schat-99db5',
    storageBucket: 'let-schat-99db5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQHP5GKKqvN37R2OpmR17p4-QJsW4b0eE',
    appId: '1:755189938867:ios:cef066e13593a6155d8ec6',
    messagingSenderId: '755189938867',
    projectId: 'let-schat-99db5',
    storageBucket: 'let-schat-99db5.appspot.com',
    androidClientId: '755189938867-m3dbr32ek8fn7qg72g1fibkhbvq7pnn6.apps.googleusercontent.com',
    iosClientId: '755189938867-d25q4dfqgj7qq21vfo2mqemh2aa364e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.letschat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQHP5GKKqvN37R2OpmR17p4-QJsW4b0eE',
    appId: '1:755189938867:ios:19b8202bdb90b64b5d8ec6',
    messagingSenderId: '755189938867',
    projectId: 'let-schat-99db5',
    storageBucket: 'let-schat-99db5.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz09Fh9bwTepccfQUuwPKsguYnCh8ZMxI',
    appId: '1:755189938867:web:e97de81a019a39745d8ec6',
    messagingSenderId: '755189938867',
    projectId: 'let-schat-99db5',
    authDomain: 'let-schat-99db5.firebaseapp.com',
    storageBucket: 'let-schat-99db5.appspot.com',
    measurementId: 'G-XQJKJSPY3P',
  );
}